target-version = "py311"
line-length = 100
extend-exclude = [".wheel-venv", "src/intryc_delivery/contract/semantic.py", "src/intryc_delivery/contract/json_payload.py"]

force-exclude = true

[lint]
select = ["E4", "E7", "E9", "F", "I"]
